# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Kevin Lin
description: My personal portfolio
url: https://kevinlinvxd.github.io # the base hostname & protocol for your site
author: Kevin Lin
email: kevinlin.vxd@gmail.com

google-analytics:
  id: ""

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap
